### ISSUE TITLE
ACL for pages in category causes problem with VisualEditor/Parsoid extenstion

### ISSUE THREAD

**Issue by modliszka** [HaloACL/HaloACL#11]
When I want edit any pages who are in ACL Category/My_category I've such error:

Error loading data from server: parsoidserver-http-bad-status: 500: API response is missing query for: My_page_in_category Error: API response is missing query for: My_page_in_category 
 at TemplateRequest._handleJSON (/home/abclinux/parsoid/lib/mediawiki.ApiRequest.js:277:11)
 at TemplateRequest.ApiRequest._handleBody (/home/abclinux/parsoid/lib/mediawiki.ApiRequest.js:204:7)
 at TemplateRequest.ApiRequest._requestCB (/home/abclinux/parsoid/lib/mediawiki.ApiRequest.js:165:8)
 at Request.self.callback (/home/abclinux/parsoid/node_modules/request/request.js:123:22)
 at Request.emit (events.js:98:17)
 at Request.<anonymous> (/home/abclinux/parsoid/node_modules/request/request.js:1047:14)
 at Request.emit (events.js:117:20)
 at IncomingMessage.<anonymous> (/home/abclinux/parsoid/node_modules/request/request.js:998:12)
 at IncomingMessage.emit (events.js:117:20)
 at _stream_readable.js:944:16. Would you like to retry?

When I delete this ACL everything is ok. What could be wrong? Maybe it is not HaloACL fault?

**Comment by hermannschwaerzlerUIBK** [comment]
Hi,
how exactly did you configure VisualEditor/Parsoid?
If you are using parsoid you have to consider how that works: If you edit a page, VisualEditor makes a serverside request to your Parsoid which in turn fetches the page using the MediaWiki-API, parses it and sends the result back.
So most probably HaloACL blocks the serverside API-request for the page as it is not from you but from Parsoid...

**Comment by modliszka** [comment]
That's my configuration from localSettings.php:
require_once "$IP/extensions/VisualEditor/VisualEditor.php";
	$wgVisualEditorParsoidPrefix = 'localhost';#'10.0.0.98';
	$wgVisualEditorParsoidForwardCookies = true;
	$wgVisualEditorParsoidURL = 'http://localhost:8000';
	$wgVisualEditorParsoidHTTPProxy = false;

And HaloACL:
# HaloACL
include_once('extensions/HaloACL/includes/HACL_Initialize.php');
	enableHaloACL(); 
	$wgMainCacheType = CACHE_MEMCACHED;
	$wgMemCachedServers = array('localhost:11211');

And if it is the serverside problem, do I have to change something or something has to be changed in extension's code?

**Comment by hermannschwaerzlerUIBK** [comment]
First try adding this:
`$wgVisualEditorParsoidForwardCookies = true;`

You should read this:
https://www.mediawiki.org/wiki/Extension:VisualEditor#Linking_with_Parsoid_in_private_wikis

If Cookie-forwarding does not help: for HaloACL most probably the workaround with changing just the `$wgGroupPermissions` based on the remote host will not work. But you might get it working if you include and activate HaloACL only when requests are *not* originating from localhost == Parsoid. Maybe like this:

```php
$local_ip = '127.0.0.1';
if ( $_SERVER['REMOTE_ADDR'] != $local_ip ) {
   include_once('extensions/HaloACL/includes/HACL_Initialize.php');
   enableHaloACL();
}
```

**Comment by modliszka** [comment]
Ok, it works, but then I can't change anything in special HaloACL page, when I am on server, because this extension is not enable. Also everybody who has account and who is logged in MediaWiki on server can edit every page (what I don't want).

**Comment by hermannschwaerzlerUIBK** [comment]
Did you try only `$wgVisualEditorParsoidForwardCookies = true;`?
I.e. without that workaround of disabling HaloACL when requests come from localhost?

**Comment by modliszka** [comment]
With only these lines in my code:
```php
require_once "$IP/extensions/VisualEditor/VisualEditor.php";
$wgVisualEditorParsoidForwardCookies = true;
include_once('extensions/HaloACL/includes/HACL_Initialize.php');
enableHaloACL(); 
```
nothing has changed, the error still is.

I don't get your question. I used your workaround and then (when my requests were from localhost) I could edit these pages which should be protected by HaloACL, and so did every other user (who didn't have permission). So when requests come from localhost the HaloACL should works too.

**Comment by hermannschwaerzlerUIBK** [comment]
Sorry I had been a bit fuzzy. After some thinking about it it's quite clear that the workaround-way of using Parsoid (disabling access-restrictions when requests originate from Parsoid) is a no-go for wikis that want to use HaloACL.

I found some time to look into cookie-forwarding and I think I found a solution to make it work.
Setting `$wgVisualEditorParsoidForwardCookies = true` is not enough!
Additiononally you have to use a non-blocking session store because your browser and Parsoid will use the same session cookie at the same time - which leads to deadlocks when you use the default PHP-session-store. 
I got it working by adding this to my LocalSettings (in addition to enabling VisualEditor and `$wgVisualEditorParsoidForwardCookies = true;`). I did not test this with HaloACL installed but it should work for that as well:
```php
$wgSessionsInObjectCache = true;
$wgSessionCacheType = CACHE_DB;
```
Which cache type you are using is up to your performance needs: CACHE_DB is a simple to use non-blocking store but is probably not as fast as CACHE_MEMCACHED. But for that you have to install and run memcached.

**Comment by modliszka** [comment]
I added these lines of code to LocalSettings.php but unfortunately it still doesn't work. :(

**Comment by hermannschwaerzlerUIBK** [comment]
Could you elaborate on "still doesn't work"? What exactly does happen? Error-messages? Does the loading-bar of VisualEditor show up, when you click on "Edit"?
Do you see anything in the error-log of your webserver?
Do you see requests coming from Parsoid in the access-log of your webserver?
Which browser are you using? Please test it with a different one.

**Comment by modliszka** [comment]
"Still doesn't work" means for me, that there is still this error, which I was writing about in my first comment (it is still the same message when I click on edit button and loading-bar doesn't show up).  
I won't have access to server with MediaWiki in the nearest days, so for another questions I'll answer later. And I use Firefox and IE, so I'll also check different browser next time.

**Comment by worp1900** [comment]
Hi,
maybe I can provide some assistance with finding the issue, as the error occurs on our testing-server as well.
We were playing around with visualEditor for a while and introduced HaloACL two weeks ago. Since then, we are running into the same issue.

When we limit access to a specific page by granting full-rights to one user, the user can access the page just fine. Upon clicking on "Bearbeiten" (German for edit), the loading bar of visualEditor appears and stays visible and animated for quite some time (approx. 15 seconds). Then the error message appears and the animation of the loading bar stops. (Situation displayed in the screenshot)

![2015-04-07 13_53_59-mediawiki entw-win81-08 entw-win81-08 - remote desktop connection manager v2](https://cloud.githubusercontent.com/assets/3766070/7022666/6f9e0ff0-dd2e-11e4-8df8-291f8444793c.png)

Clicking on "OK" will behave identically to clicking on "Bearbeiten" again: The loading bar will be animated until the error re-occurs. This does not changed if clicked multiple times.

If the Cancel button is invoked, the error message disappears, the loading bar also disappears and the site is simply open and readable. The user can click on "Bearbeiten" again, which will repeat the process described above identically.

Maybe the commandline output of node will help with the problem:
![2015-04-07 14_03_49-mediawiki entw-win81-08 entw-win81-08 - remote desktop connection manager v2](https://cloud.githubusercontent.com/assets/3766070/7022738/2cd57496-dd2f-11e4-8d82-f1347c32433d.png)

I have tried setting 
```php
     $wgVisualEditorParsoidForwardCookies = true;
     $wgSessionsInObjectCache = true;
     $wgSessionCacheType = CACHE_DB;
```

in LocalSettings.php, which does not seem to have any effect.

I would be more than happy to provide assistance as needed.

**Comment by hermannschwaerzlerUIBK** [comment]
Thanks for your assistance worp1900!
Just a quick back-check: If you use those settings for `$wgVisualEditorParsoidForwardCookies`, `$wgSessionsInObjectCache` and `$wgSessionCacheType` you mentioned above but *disable* HaloACL, VisualEditor is working, isn't it?

What do you see in the Server access-logs for those failing requests? Is Parsoid trying to get the page via MW-API?

**Comment by worp1900** [comment]
My pleasure! Thank your for the amazingly fast reponse! :D

Yes, when I keep ```$wgVisualEditorParsoidForwardCookies```, ```$wgSessionsInObjectCache``` and ```$wgSessionCacheType``` but disable HaloACL by commenting:
```
#include_once('extensions/HaloACL/includes/HACL_Initialize.php');
#enableHaloACL(); 
```
The VE works.

Yes, it looks like Parsoid is trying to get them via the MW-API. I have requests going to /w/api.php:

```

::1 - - [07/Apr/2015:14:53:03 +0200] "GET /w/index.php/Hauptseite HTTP/1.1" 200 17566 "http://localhost/w/index.php/Skript:00_00_00_01:de" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
::1 - - [07/Apr/2015:14:53:06 +0200] "GET /w/index.php/Skript:00_00_00_01:de HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
127.0.0.1 - - [07/Apr/2015:14:53:11 +0200] "GET /w/api.php?format=json&action=query&prop=revisions&rvprop=content%7Cids%7Ctimestamp%7Cuser%7Cuserid%7Csize%7Csha1%7Ccontentmodel%7Ccomment&revids=979 HTTP/1.1" 200 106 "-" "Parsoid/0.1"
::1 - - [07/Apr/2015:14:53:09 +0200] "GET /w/api.php?format=json&action=visualeditor&paction=parse&page=Skript%3A00_00_00_01%3Ade HTTP/1.1" 200 63 "http://localhost/w/index.php/Skript:00_00_00_01:de?veaction=edit" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
127.0.0.1 - - [07/Apr/2015:14:54:33 +0200] "GET /w/api.php?format=json&action=query&prop=revisions&rvprop=content%7Cids%7Ctimestamp%7Cuser%7Cuserid%7Csize%7Csha1%7Ccontentmodel%7Ccomment&revids=979 HTTP/1.1" 200 106 "-" "Parsoid/0.1"
::1 - - [07/Apr/2015:14:54:31 +0200] "GET /w/api.php?format=json&action=visualeditor&paction=parse&page=Skript%3A00_00_00_01%3Ade HTTP/1.1" 200 63 "http://localhost/w/index.php/Skript:00_00_00_01:de?veaction=edit" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
```

**Comment by worp1900** [comment]
As additional references i found:
http://www.mediawiki.org/wiki/Extension_talk:Lockdown#Lockdown_and_VisualEditor_-_can.27t_edit_protected_pages_39752

I also tried adding these configuration settings:
http://www.mediawiki.org/wiki/Talk:Parsoid#Running_Parsoid_on_a_.22private.22_wiki_-_AccessDeniedError

And its short form:
https://www.mediawiki.org/wiki/User:Andru/Allow_Parsoid_Server
With some modification:
```
if ($_SERVER['REMOTE_ADDR'] == '::1' || $_SERVER['REMOTE_ADDR'] == '127.0.0.1') {
 $wgGroupPermissions['*']['read'] = true;
 $wgGroupPermissions['*']['edit'] = true;
}
```

Since it is a private wiki not accessible to public. Sadly that didn't impact anything :/

**Comment by hermannschwaerzlerUIBK** [comment]
OK. I think I found the problem: When HaloACL is installed and enabled cookies are no longer forwarded to Parsoid due to this code in `extensions/VisualEditor/ApiVisualEditor.php`:
```php
if ( $wgVisualEditorParsoidForwardCookies && !User::isEveryoneAllowed( 'read' ) ) {
  $req->setHeader( 'Cookie', $this->getRequest()->getHeader( 'Cookie' ) );
}
```
It's strange but when HaloACL is enabled `User::isEveryoneAllowed('read')` returns `true` (!) thus the cookie is not forwarded.

As a quick and dirty hack: are you willing to replace in `extensions/VisualEditor/ApiVisualEditor.php` the two occurrences of 
`if ( $wgVisualEditorParsoidForwardCookies && !User::isEveryoneAllowed( 'read' ) ) {` 
with 
`if ( $wgVisualEditorParsoidForwardCookies ) {`.
Does that work for you?

If yes we definitely found the problem but have to think about a better way to handle it. :-)

**Comment by worp1900** [comment]
I will check that out. Gimme about an hour!
Thanks in advance for putting in the time!

**Comment by worp1900** [comment]
Nevermind the hour. I had to check directly ^^

While the suggested change didn't do anything, I just went ahead and commented out both occasions:
```php
			// Forward cookies, but only if configured to do so and if there are read restrictions
//			if ( $wgVisualEditorParsoidForwardCookies && !User::isEveryoneAllowed( 'read' ) ) {
				$req->setHeader( 'Cookie', $this->getRequest()->getHeader( 'Cookie' ) );
//			}
```

Which did the trick.

It is working now.

Obviously it's even dirtier than what you suggested :D

**Comment by hermannschwaerzlerUIBK** [comment]
OK. Good to hear it's working now!
But if my suggestion did not work you haven't set `$wgVisualEditorParsoidForwardCookies` to `true` in `LocalSettings.php`, have you?

I will try to find why `User::isEveryoneAllowed( 'read' )` returns `true` with HaloACL (which is counter-intuitive IMO). But maybe it's time for wojteque to jump in. :-)

**Comment by worp1900** [comment]
That's what I thought of as well, but my htdocs/w/LocalSettings.php states:

```php
// Forward users' Cookie: headers to Parsoid. Required for private wikis (login required to read).
// If the wiki is not private (i.e. $wgGroupPermissions['*']['read'] is true) this configuration
// variable will be ignored.
//
// This feature requires a non-locking session store. The default session store will not work and
// will cause deadlocks when trying to use this feature. If you experience deadlock issues, enable
// $wgSessionsInObjectCache like this: 
//$wgSessionsInObjectCache = true;
//
// WARNING: ONLY enable this on private wikis and ONLY IF you understand the SECURITY IMPLICATIONS
// of sending Cookie headers to Parsoid over HTTP. For security reasons, it is strongly recommended
// that $wgVisualEditorParsoidURL be pointed to localhost if this setting is enabled.
$wgVisualEditorParsoidForwardCookies = true;
$wgSessionsInObjectCache = true;
$wgSessionCacheType = CACHE_DB;
```
